### ISSUE TITLE
[BUG] 网易大师客户端连接 smtp proxy 报错

### ISSUE THREAD

**Issue by wsgehaishan520** [dreamhunter2333/cloudflare_temp_email#237]
mtp_proxy_server  | Unhandled Error
smtp_proxy_server  | Traceback (most recent call last):
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 773, in dispatchCommand
smtp_proxy_server  |     self.__doCommand(tag, fn, [self, tag], parseargs, rest, uid)
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 784, in __doCommand
smtp_proxy_server  |     maybeDeferred(arg, self, line).addCallback(
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/internet/defer.py", line 623, in addCallback
smtp_proxy_server  |     return self.addCallbacks(callback, callbackArgs=args, callbackKeywords=kwargs)
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/internet/defer.py", line 536, in addCallbacks
smtp_proxy_server  |     self._runCallbacks()
smtp_proxy_server  | ---  ---
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/internet/defer.py", line 1078, in _runCallbacks
smtp_proxy_server  |     current.result = callback(  # type: ignore[misc]
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 803, in __cbDispatch
smtp_proxy_server  |     self.__doCommand(tag, fn, args, parseargs, rest, uid)
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 798, in __doCommand
smtp_proxy_server  |     handler(*args)
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 1358, in do_CREATE
smtp_proxy_server  |     self.sendNegativeResponse(tag, networkString(str(c)))
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/python/compat.py", line 462, in networkString
smtp_proxy_server  |     return s.encode("ascii")
smtp_proxy_server  | builtins.UnicodeEncodeError: 'ascii' codec can't encode characters in position 17-19: ordinal not in range(128)
smtp_proxy_server  | 
smtp_proxy_server  | 2024-05-14 19:18:11,138 - imap_server - INFO - New mailbox: 已发送, 2
smtp_proxy_server  | Unhandled Error
smtp_proxy_server  | Traceback (most recent call last):
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 773, in dispatchCommand
smtp_proxy_server  |     self.__doCommand(tag, fn, [self, tag], parseargs, rest, uid)
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 784, in __doCommand
smtp_proxy_server  |     maybeDeferred(arg, self, line).addCallback(
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/internet/defer.py", line 623, in addCallback
smtp_proxy_server  |     return self.addCallbacks(callback, callbackArgs=args, callbackKeywords=kwargs)
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/internet/defer.py", line 536, in addCallbacks
smtp_proxy_server  |     self._runCallbacks()
smtp_proxy_server  | ---  ---
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/internet/defer.py", line 1078, in _runCallbacks
smtp_proxy_server  |     current.result = callback(  # type: ignore[misc]
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 803, in __cbDispatch
smtp_proxy_server  |     self.__doCommand(tag, fn, args, parseargs, rest, uid)
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 798, in __doCommand
smtp_proxy_server  |     handler(*args)
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 1358, in do_CREATE
smtp_proxy_server  |     self.sendNegativeResponse(tag, networkString(str(c)))
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/python/compat.py", line 462, in networkString
smtp_proxy_server  |     return s.encode("ascii")
smtp_proxy_server  | builtins.UnicodeEncodeError: 'ascii' codec can't encode characters in position 17-19: ordinal not in range(128)
smtp_proxy_server  | 
smtp_proxy_server  | 2024-05-14 19:18:33,212 - imap_server - INFO - New mailbox: INBOX, 0
smtp_proxy_server  | 2024-05-14 19:18:40,505 - imap_server - INFO - New mailbox: INBOX, 0
smtp_proxy_server  | Unhandled Error
smtp_proxy_server  | Traceback (most recent call last):
smtp_proxy_server  |   File "/app/imap_server.py", line 194, in start_imap_server
smtp_proxy_server  |     reactor.run()
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/internet/base.py", line 695, in run
smtp_proxy_server  |     self.mainLoop()
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/internet/base.py", line 705, in mainLoop
smtp_proxy_server  |     self.runUntilCurrent()
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/internet/base.py", line 1090, in runUntilCurrent
smtp_proxy_server  |     call.func(*call.args, **call.kw)
smtp_proxy_server  | ---  ---
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 5554, in go
smtp_proxy_server  |     r = next(i)
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 2249, in spew
smtp_proxy_server  |     yield f(id, msg, write, flush)
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 2125, in spew_internaldate
smtp_proxy_server  |     idate = msg.getInternalDate()
smtp_proxy_server  | builtins.AttributeError: 'SimpleMessage' object has no attribute 'getInternalDate'
smtp_proxy_server  | 
smtp_proxy_server  | 2024-05-14 19:19:28,994 - imap_server - INFO - New mailbox: INBOX, 0
smtp_proxy_server  | 2024-05-14 19:19:30,300 - imap_server - INFO - New mailbox: 草稿箱, 1
smtp_proxy_server  | Unhandled Error
smtp_proxy_server  | Traceback (most recent call last):
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 773, in dispatchCommand
smtp_proxy_server  |     self.__doCommand(tag, fn, [self, tag], parseargs, rest, uid)
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 784, in __doCommand
smtp_proxy_server  |     maybeDeferred(arg, self, line).addCallback(
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/internet/defer.py", line 623, in addCallback
smtp_proxy_server  |     return self.addCallbacks(callback, callbackArgs=args, callbackKeywords=kwargs)
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/internet/defer.py", line 536, in addCallbacks
smtp_proxy_server  |     self._runCallbacks()
smtp_proxy_server  | ---  ---
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/internet/defer.py", line 1078, in _runCallbacks
smtp_proxy_server  |     current.result = callback(  # type: ignore[misc]
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 803, in __cbDispatch
smtp_proxy_server  |     self.__doCommand(tag, fn, args, parseargs, rest, uid)
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 798, in __doCommand
smtp_proxy_server  |     handler(*args)
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 1358, in do_CREATE
smtp_proxy_server  |     self.sendNegativeResponse(tag, networkString(str(c)))
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/python/compat.py", line 462, in networkString
smtp_proxy_server  |     return s.encode("ascii")
smtp_proxy_server  | builtins.UnicodeEncodeError: 'ascii' codec can't encode characters in position 17-19: ordinal not in range(128)
smtp_proxy_server  | 
smtp_proxy_server  | 2024-05-14 19:19:30,481 - imap_server - INFO - New mailbox: 已发送, 2
smtp_proxy_server  | Unhandled Error
smtp_proxy_server  | Traceback (most recent call last):
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 773, in dispatchCommand
smtp_proxy_server  |     self.__doCommand(tag, fn, [self, tag], parseargs, rest, uid)
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 784, in __doCommand
smtp_proxy_server  |     maybeDeferred(arg, self, line).addCallback(
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/internet/defer.py", line 623, in addCallback
smtp_proxy_server  |     return self.addCallbacks(callback, callbackArgs=args, callbackKeywords=kwargs)
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/internet/defer.py", line 536, in addCallbacks
smtp_proxy_server  |     self._runCallbacks()
smtp_proxy_server  | ---  ---
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/internet/defer.py", line 1078, in _runCallbacks
smtp_proxy_server  |     current.result = callback(  # type: ignore[misc]
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 803, in __cbDispatch
smtp_proxy_server  |     self.__doCommand(tag, fn, args, parseargs, rest, uid)
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 798, in __doCommand
smtp_proxy_server  |     handler(*args)
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/mail/imap4.py", line 1358, in do_CREATE
smtp_proxy_server  |     self.sendNegativeResponse(tag, networkString(str(c)))
smtp_proxy_server  |   File "/usr/local/lib/python3.12/site-packages/twisted/python/compat.py", line 462, in networkString
smtp_proxy_server  |     return s.encode("ascii")
smtp_proxy_server  | builtins.UnicodeEncodeError: 'ascii' codec can't encode characters in position 17-19: ordinal not in range(128)
smtp_proxy_server  | 
smtp_proxy_server  | 2024-05-14 19:19:50,743 - imap_server - INFO - New mailbox: INBOX, 0

## 复现步骤

上面是网易大师客户端连接smtp后端的报错代码，看了一下好像是编码问题，看看能不能修复一下
雷鸟测试收发都是正常的，网页也都是正常的。网易这个客户端，收发都不正常
## 部署方式

docker部署的smtp服务器

**Comment by dreamhunter2333** [comment]
OK 我测试一下
