### ISSUE TITLE
[BUG]安装imap代理服务出错

### ISSUE THREAD

**Issue by ltkun** [dreamhunter2333/cloudflare_temp_email#330]
本地运行python的时候出错 
## 复现步骤
root@pve105:~/cloudflare_temp_email/smtp_proxy_server# ./venv/bin/python3 main.py
Traceback (most recent call last):
  File "/root/cloudflare_temp_email/smtp_proxy_server/main.py", line 5, in <module>
    from imap_server import start_imap_server
  File "/root/cloudflare_temp_email/smtp_proxy_server/imap_server.py", line 13, in <module>
    from parse_email import generate_email_model, parse_email
  File "/root/cloudflare_temp_email/smtp_proxy_server/parse_email.py", line 60
    message['From'] = f"{email_json["from"]['name']} <{
                                         ^
SyntaxError: unterminated string literal (detected at line 60)

## 部署方式

- [ ] cli 部署

**Comment by dreamhunter2333** [comment]
请先修改成 `message['From'] = f"{email_json["from"]['name']} <{email_json["from"]['email']}>"` 尝试下

**Comment by ltkun** [comment]
上面提示没了哈 新错误又出现了 sorry不是程序员看不明白代码
root@pve105:~/cloudflare_temp_email/smtp_proxy_server# ./venv/bin/python3 main.py
Traceback (most recent call last):
  File "/root/cloudflare_temp_email/smtp_proxy_server/main.py", line 5, in <module>
    from imap_server import start_imap_server
  File "/root/cloudflare_temp_email/smtp_proxy_server/imap_server.py", line 13, in <module>
    from parse_email import generate_email_model, parse_email
  File "/root/cloudflare_temp_email/smtp_proxy_server/parse_email.py", line 51
    message['From'] = f"{email_json["from_name"]} <{item["address"]}>" if email_json.get(
                                     ^^^^^^^^^
SyntaxError: f-string: unmatched '['

**Comment by dreamhunter2333** [comment]
> python3

python3 是什么版本，文件是复制粘贴上去的么

**Comment by dreamhunter2333** [comment]
> > python3
> 
> python3 是什么版本，文件是复制粘贴上去的么

本地运行是否报错，我测试本地和服务器都可以正常运行

**Comment by ltkun** [comment]
就是本地运行出错了 应该还没有部署

![1](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/20526705/f98e2064-4c7c-4de9-9e3d-64694b5bf578)

**Comment by dreamhunter2333** [comment]
> 就是本地运行出错了 应该还没有部署
> 
> 
> 
> ![1](https://github.com/dreamhunter2333/cloudflare_temp_email/assets/20526705/f98e2064-4c7c-4de9-9e3d-64694b5bf578)
> 
> 

我再测试下，看看能不能复现

**Comment by dreamhunter2333** [comment]
> 就是本地运行出错了 应该还没有部署
> 
> ![1](https://private-user-images.githubusercontent.com/20526705/346268511-f98e2064-4c7c-4de9-9e3d-64694b5bf578.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNjU3MjksIm5iZiI6MTcyMDI2NTQyOSwicGF0aCI6Ii8yMDUyNjcwNS8zNDYyNjg1MTEtZjk4ZTIwNjQtNGM3Yy00ZGU5LTllM2QtNjQ2OTRiNWJmNTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDExMzAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyNjZiYWEzNWE3NDM5OTcyYjVjYmU2MmE1MTNjMGNkMGIwZDQ1OWJiNDU4MWEzNGQ0MTJlMDM4ZmQ4NDkwZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tkzrJsGf1H8bdVCEkalsGU55278TOGa_PeuZnW4QKcA)

改成单引号尝试下 
```python
        message['To'] = f'{email_json["to_name"]} <{email_json["to_mail"]}>' if email_json.get("to_name") else email_json["to_mail"]

```

**Comment by dreamhunter2333** [comment]
root cause 为 python 版本导致的 引号问题
